# Generated by Django 3.2.2 on 2021-05-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('titre_image', models.CharField(max_length=75)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'Image',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Texte',
            fields=[
                ('id_texte', models.AutoField(primary_key=True, serialize=False)),
                ('titre_texte', models.CharField(max_length=75)),
                ('texte', models.TextField()),
            ],
            options={
                'db_table': 'Texte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id_url', models.AutoField(primary_key=True, serialize=False)),
                ('titre_url', models.CharField(max_length=75)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Url',
                'managed': False,
            },
        ),
    ]
