# Generated by Django 3.2.2 on 2021-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendIhe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditeur',
            fields=[
                ('id_auditeur', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(max_length=255, upload_to='')),
                ('nom_prenom', models.CharField(max_length=150)),
                ('poste', models.CharField(max_length=150)),
                ('annee_formation', models.CharField(max_length=10)),
                ('avis', models.TextField()),
            ],
            options={
                'db_table': 'Auditeur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id_event', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150)),
                ('descriptif', models.TextField()),
                ('date_event', models.DateField()),
                ('image', models.ImageField(max_length=255, upload_to='')),
            ],
            options={
                'db_table': 'Evenement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institut',
            fields=[
                ('id_institut', models.AutoField(primary_key=True, serialize=False)),
                ('sigle', models.CharField(max_length=150)),
                ('nom_complet', models.CharField(max_length=150)),
                ('logo', models.ImageField(max_length=255, upload_to='')),
                ('presentation', models.TextField()),
                ('descriptif_formation', models.TextField()),
                ('website', models.URLField(max_length=255)),
                ('twitter', models.URLField(max_length=255)),
            ],
            options={
                'db_table': 'Institut',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Texte',
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
