# Generated by Django 3.2.2 on 2021-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendIhe', '0002_auto_20210527_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id_accueil', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('sous_titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Accueil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AutreTexte',
            fields=[
                ('id_autre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('sous_titre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'AutreTexte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id_experience', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=75)),
                ('texte', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'Experience',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedagogie',
            fields=[
                ('id_pedagogie', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100)),
                ('sous_titre', models.CharField(max_length=100)),
                ('texte', models.TextField()),
            ],
            options={
                'db_table': 'Pedagogie',
                'managed': False,
            },
        ),
    ]
